name: zego_uikits_demo
description: "demo of uikits"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  zego_zim: ^2.21.1+1

  zego_uikit: ^2.28.23
  zego_uikit_signaling_plugin: ^2.8.15
  zego_uikit_beauty_plugin: ^1.7.9
  zego_plugin_adapter: ^2.13.9

  zego_uikit_prebuilt_video_conference: ^2.10.1
  zego_uikit_prebuilt_call: ^4.17.10
  zego_uikit_prebuilt_live_audio_room: ^3.16.3
  zego_uikit_prebuilt_live_streaming: ^3.14.2
  zego_zimkit: ^1.19.2

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  circle_nav_bar: ^2.1.1
  flutter_screenutil: ^5.9.3
  device_info_plus: any
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  introduction_screen: ^3.1.14
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  flutter_local_notifications: ^18.0.1
  flutter_email_sender: ^7.0.0
  url_launcher: ^6.3.1
  lottie: ^3.1.2
  circular_countdown: ^2.1.0
  cloud_firestore: ^5.6.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.4.0
  firebase_messaging: ^15.1.3
  flutter_slidable: ^3.1.2
  flutter_dialpad:
    path: ./3rdparty/flutter_dialpad-1.0.5
  archive: ^3.4.10
  path_provider: ^2.1.2
  chunked_stream: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'

flutter:
  uses-material-design: true
  assets:
    - assets/csv/
    - assets/icon/
    - assets/images/
    - assets/call/
    - assets/live_streaming/
    - assets/audio_room/
    - assets/conference/
    - assets/chat/
    - assets/json/
    - assets/lottie/gifts/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21